Bug/hint wrong point pair highlight
SudoKuru/Frontend pull request #189
Opened 2023-04-13 23:36 UTC by danielcosentino

## Checklist for completing pull request:
- [ ] Test functionality on Android and web (iOS optional but encouraged)
- [ ] Verify that any unit tests for new functionality are created and functional.
- [ ] If needed, update the Readme

2023-04-13 23:37 UTC, Thomas-Gallant requested changes
Can you remove the console logs?

2023-04-13 23:38 UTC, danielcosentino commented
> Can you remove the console logs?

yes

2023-04-13 23:54 UTC, Thomas-Gallant approved these changes

2023-04-14 03:50 UTC, Thomas-Gallant approved these changes

2023-04-14 04:25 UTC, merged