Switching from playwright-coverage reporter to monocart reporter
Sudokuru/Frontend pull request #300
Opened 2024-07-09 02:19 UTC by Thomas-Gallant

Replacing `@bgotink/playwright-coverage` with monocart reporter

Reason for the change was upgrading to Expo 51 was causing playwright-coverage to error out:
![image](https://github.com/Sudokuru/Frontend/assets/60023923/23c70bac-429f-42d2-94a3-13d0c1bdfcbb)

monocart reporter is not encountering this issue, meaning we can up code coverage scanning with the upgrade to Expo 51

## Checklist for completing pull request:
- [ ] Test functionality on Mobile, Web, and Desktop
- [ ] Verify that any tests for new functionality are created and functional.
- [ ] If needed, update the Readme

2024-07-11 23:16 UTC, Gregory711 approved these changes

2024-07-11 23:45 UTC, Gregory711 requested changes
missing files

2024-07-14 14:40 UTC, Thomas-Gallant commented
> missing files

This has been fixed, I believe the issue was the space in the folder name "Sudoku Board" so I renamed it to "SudokuBoard".

2024-07-14 18:55 UTC, Gregory711 approved these changes

2024-07-14 18:56 UTC, merged